### ISSUE TITLE
Unable to parse QR address from monerujo android wallet

### ISSUE THREAD

**Issue by mmbyday** [fotolockr/CakeWallet#28]
the payment_id may not be empty. it's either there or it's not. when it's there it needs to be set to something valid. tx_amount also is affected. 

problem occurs when a monerujo wallet user attempts to send funds to cakewallet user

example:
monero:4AdkPJoxn7JCvAby9szgnt93MSEwdnxdhaASxbTBm6x5dCwmsDep2UYN4FhStDn5i11nsJbpU7oj59ahg8gXb1Mg3viqCuk?tx_payment_id=&tx_amount=

referenced issue:
https://github.com/m2049r/xmrwallet/issues/473

**Comment by fotolockr** [comment]
This is fixed in the new version.
