### ISSUE TITLE
Scanning a QR with payment id and amount 

### ISSUE THREAD

**Issue by anthfran** [fotolockr/CakeWallet#3]
When a QR code has a payment ID and/or amount, they are added to the end of the payment address rather than being put into the proper fields.

**Comment by fotolockr** [comment]
Thanks. Yeah, we are not parse additional info and as you said if exist additional fields it's parsing wrong.

**Comment by fotolockr** [comment]
Fixed it in release-1.0.2 branch. Please test it and write feedback if you've time for it.

**Comment by anthfran** [comment]
Works now. thanks!
